In [2]:
import numpy as np
import pandas as pd
import yfinance as yf
import datetime
import warnings

warnings.filterwarnings('ignore')

In [3]:
# European Tickers (Italy, France, Germany, Spain, the Netherlands), last 5 years
european_tickers = ['ENEL.MI', 'ISP.MI', 'ENI.MI','AIR.PA', 'MC.PA', 'OR.PA','SAP.DE', 'SIE.DE', 'ALV.DE','IBE.MC', 'SAN.MC','ASML.AS']

end_date = datetime.date.today()
start_date = end_date - datetime.timedelta(days=5*365)

print(f"Downloading data from {start_date} to {end_date}")

Downloading data from 2021-04-01 to 2026-03-31

In [4]:
# Downloading data
price_data = yf.download(european_tickers, start=start_date, end=end_date)

# Checking for NaN
print("NaN values for ticket")
print(price_data.isna().sum())

# Filling NaNs
price_data = price_data.fillna(method='ffill')

price_data.head()

[*********************100%***********************]  12 of 12 completed

NaN values for ticket
Price   Ticker
Close   AIR.PA      0
        ALV.DE      7
        ASML.AS     0
        ENEL.MI    10
        ENI.MI     10
        IBE.MC      2
        ISP.MI     10
        MC.PA       0
        OR.PA       0
        SAN.MC      2
        SAP.DE      7
        SIE.DE      7
High    AIR.PA      0
        ALV.DE      7
        ASML.AS     0
        ENEL.MI    10
        ENI.MI     10
        IBE.MC      2
        ISP.MI     10
        MC.PA       0
        OR.PA       0
        SAN.MC      2
        SAP.DE      7
        SIE.DE      7
Low     AIR.PA      0
        ALV.DE      7
        ASML.AS     0
        ENEL.MI    10
        ENI.MI     10
        IBE.MC      2
        ISP.MI     10
        MC.PA       0
        OR.PA       0
        SAN.MC      2
        SAP.DE      7
        SIE.DE      7
Open    AIR.PA      0
        ALV.DE      7
        ASML.AS     0
        ENEL.MI    10
        ENI.MI     10
        IBE.MC      2
        ISP.MI     10
        MC.PA       0
        OR.PA       0
        SAN.MC      2
        SAP.DE      7
        SIE.DE      7
Volume  AIR.PA      0
        ALV.DE      7
        ASML.AS     0
        ENEL.MI    10
        ENI.MI     10
        IBE.MC      2
        ISP.MI     10
        MC.PA       0
        OR.PA       0
        SAN.MC      2
        SAP.DE      7
        SIE.DE      7
dtype: int64

Price           Close                                                        \
Ticker         AIR.PA      ALV.DE     ASML.AS   ENEL.MI    ENI.MI    IBE.MC
Date
2021-04-01  93.831169  170.278732  505.143219  6.180105  7.482129  8.901553
2021-04-06  94.092796  171.180328  508.960510  6.267293  7.414174  9.111285
2021-04-07  93.943314  172.473862  500.944061  6.290740  7.401433  9.070952
2021-04-08  94.186249  171.533096  507.719971  6.338363  7.262693  9.304888
2021-04-09  94.466560  171.493881  511.060089  6.296601  7.220221  9.284719

Price                                                   ...   Volume  \
Ticker        ISP.MI       MC.PA       OR.PA    SAN.MC  ...  ASML.AS
Date                                                    ...
2021-04-01  1.542552  523.988403  300.982849  2.414108  ...  1336363
2021-04-06  1.532570  528.662720  307.767365  2.448859  ...   947731
2021-04-07  1.530906  529.029419  307.349182  2.470211  ...   861199
2021-04-08  1.505951  537.186646  315.620758  2.446765  ...   775805
2021-04-09  1.499629  539.203003  314.551910  2.430856  ...   539892

Price                                                                       \
Ticker         ENEL.MI      ENI.MI      IBE.MC      ISP.MI   MC.PA   OR.PA
Date
2021-04-01  17274657.0  15858721.0  11232311.0  45900385.0  318700  330383
2021-04-06  34901158.0  19947182.0  20490728.0  93212545.0  307550  400388
2021-04-07  16198310.0  12034489.0   9638266.0  68544001.0  257919  274918
2021-04-08  28851808.0  18608692.0  13829802.0  97993978.0  338943  386573
2021-04-09  19005098.0  11528097.0  10409436.0  64674105.0  297019  283493

Price
Ticker          SAN.MC     SAP.DE     SIE.DE
Date
2021-04-01  26423239.0  2751618.0  1483387.0
2021-04-06  42587454.0  3124199.0  1229809.0
2021-04-07  41405003.0  2120500.0  1035626.0
2021-04-08  33387402.0  2867753.0  1254714.0
2021-04-09  32749030.0  2369418.0  1385885.0

[5 rows x 60 columns]

In [6]:
import pandas as pd

# ESG Risk scores (Sustainalytics via Morningstar)
# Lower score = Better (lower ESG risk)

esg_scores_dict = {
    'ENEL.MI': 17.39,  # Utilities
    'ISP.MI': 8.09,   # Finance
    'ENI.MI': 24.91,   # Energy (Oil & Gas)
    'AIR.PA': 20.33,   # Aerospace
    'MC.PA': 13.55,    # Luxury (LVMH)
    'OR.PA': 16.90,    # Consumer goods (L'Oreal)
    'SAP.DE': 11.23,    # Tech 
    'SIE.DE': 22.94,   # Automation and digitalization 
    'ALV.DE': 13.16,   # Assicurazioni
    'IBE.MC': 20.32,   # Utilities 
    'SAN.MC': 9.89,   # Finance
    'ASML.AS': 8.93   # Tech
}

print("Creating hardcoded ESG dataset...")

# Converting in Pandas DataFrame
esg_df = pd.DataFrame(list(esg_scores_dict.items()), columns=['Ticker', 'ESG_Risk_Score'])
esg_df.set_index('Ticker', inplace=True)

display(esg_df)

Creating hardcoded ESG dataset...

         ESG_Risk_Score
Ticker
ENEL.MI           17.39
ISP.MI             8.09
ENI.MI            24.91
AIR.PA            20.33
MC.PA             13.55
OR.PA             16.90
SAP.DE            11.23
SIE.DE            22.94
ALV.DE            13.16
IBE.MC            20.32
SAN.MC             9.89
ASML.AS            8.93

In [7]:
# Saving in .CSV format
price_data.to_csv('european_prices_5Y.csv')
esg_df.to_csv('european_esg_scores.csv')

print("Data saved!")

Data saved!